# Generated by Django 5.0 on 2023-12-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("film1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster_url",
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                default="movie_posters/default_poster.jpg", upload_to="movie_posters/"
            ),
        ),
    ]
