# Generated by Django 5.0.1 on 2024-01-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film1', '0005_remove_favoritemovie_movie_id_favoritemovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movie_posters/Walter Mitty.jfif', upload_to='movie_posters/'),
        ),
    ]
